export enum NotificationType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',

  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  MEETING_CREATED = 'MEETING_CREATED',
  MEETING_CANCELLED = 'MEETING_CANCELLED',
  MEETING_REMINDER = 'MEETING_REMINDER',

  CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED',

  TRAINING_REQUEST_CREATED = 'TRAINING_REQUEST_CREATED',
  TRAINING_REQUEST_ACCEPTED = 'TRAINING_REQUEST_ACCEPTED',
  TRAINING_REQUEST_REJECTED = 'TRAINING_REQUEST_REJECTED',

  FILE_UPLOADED = 'FILE_UPLOADED',
}