export enum NotificationType {
  USER_REGISTERED = 'USER_REGISTERED',

  PAYMENT_APPROVED = 'PAYMENT_APPROVED',

  MEETING_CREATED = 'MEETING_CREATED',

  TRAINING_REQUEST_CREATED = 'TRAINING_REQUEST_CREATED',

  TRAINING_REQUEST_ACCEPTED = 'TRAINING_REQUEST_ACCEPTED',

  TRAINING_REQUEST_REJECTED = 'TRAINING_REQUEST_REJECTED',
}