export enum NotificationType {

  USER_REGISTERED =
    'USER_REGISTERED',

  PAYMENT_APPROVED =
    'PAYMENT_APPROVED',

  MEETING_CREATED =
    'MEETING_CREATED',

  TRAINING_REQUEST_CREATED =
    'TRAINING_REQUEST_CREATED',

  REQUEST_IN_REVIEW =
    'REQUEST_IN_REVIEW',

  REQUEST_AWAITING_PAYMENT =
    'REQUEST_AWAITING_PAYMENT',

  REQUEST_SCHEDULED =
    'REQUEST_SCHEDULED',

  REQUEST_CONFIRMED =
    'REQUEST_CONFIRMED',

  REQUEST_CANCELLED =
    'REQUEST_CANCELLED',
}